repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.2
  hooks:
    - id: poetry-check
      args: ["-C", "./backend"]
    - id: poetry-lock
      args: ["-C", "./backend"]
    - id: poetry-export
      args: ["-C", "./backend", "-f", "requirements.txt", "-o", "./backend/requirements.txt"]
    - id: poetry-install
      args: ["-C", "./backend"]